services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=projectDB
      - DB_USER=db_user
      - DB_PASS=userpass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_DB=projectDB
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=userpass